version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./container/go/Dockerfile
    volumes: 
      - ./app:/go/src/app
    tty: true 
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - metis-network
  postgres:
    build:
      context: .
      dockerfile: ./container/postgres/Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-store:/var/lib/postgres/data
      - ./database/init:/docker-entorypoint-initdb.d
    ports:
      - 5432:5432
    networks:
    - metis-network
volumes:
  db-store:
networks:
  metis-network:
    external: true


